# Generated by Django 4.2.6 on 2023-10-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('nim', models.CharField(max_length=255)),
                ('alamat', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_mahasiswa')),
            ],
        ),
    ]
